/*
 *  FSCWNamedColors.h
 *  FractalStream
 *
 *  Created by Matt Noonan on 2/20/08.
 *  Copyright 2008 __MyCompanyName__. All rights reserved.
 *
 */

#ifndef FSCW_Named_Colors
#define FSCW_Named_Colors
	const FSCW_named_color named_color[] = { 
		{ @"blue",		0.0, 0.0, 1.0 },
		{ @"red",		1.0, 0.0, 0.0 },
		{ @"green",		0.0, 1.0, 0.0 },
		{ @"yellow",	1.0, 1.0, 0.0 },
		{ @"purple",	0.4, 0.0, 1.0 },
		{ @"cyan",		0.0, 1.0, 1.0 },
		{ @"orange",	1.0, 0.4, 0.0 },
		{ @"lime",		0.4, 1.0, 0.0 },
		{ @"aqua",		0.0, 0.4, 1.0 },
		{ @"pink",		1.0, 0.0, 0.4 },
		{ @"white",		1.0, 1.0, 1.0 },
		{ @"grey",		0.5, 0.5, 0.5 },
		{ @"black",		0.0, 0.0, 0.0 },
		{ nil, 0.0, 0.0, 0.0 }
	};
#endif
